language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore=main,main.go,/example/,./example/
# https://docs.travis-ci.com/user/deployment/releases/